#!/bin/bash

##########################################################################
#
#  Script:    prep_spm_dcm.pbs
#  Author:    Sebastien Naze
#  Created:   2022-02
#
##########################################################################

#PBS -N prep_spm_dcm
#PBS -l ncpus=2,mem=32gb,walltime=1:30:00
#PBS -m abe
#PBS -M sebastien.naze@qimrberghofer.edu.au
#PBS -o /working/lab_lucac/sebastiN/projects/OCDbaseline/.pbs_logs/
#PBS -e /working/lab_lucac/sebastiN/projects/OCDbaseline/.pbs_logs/
#
# Script to prepare individual subjects files to perform functional analysis and DCM
#

module load fsl/6.0.1
module load miniconda3/current

source activate /mnt/lustre/working/lab_lucac/sebastiN/projects/OCDbaseline/envs/hpc

proj_dir=/mnt/lustre/working/lab_lucac/sebastiN/projects/OCDbaseline/
lukeH_proj_dir=/mnt/lustre/working/lab_lucac/lukeH/projects/OCDbaseline/
pp_dir=${proj_dir}postprocessing/

# load specific subject from subject list
mapfile -t subj_array < ${proj_dir}docs/code/subject_list_all.txt
IDX=$((PBS_ARRAY_INDEX-1))  # double parenthesis needed for arithmetic operations
subj=${subj_array[$IDX]}
echo "Current subject: " ${subj}

echo 'Denoising '${subj}
python ${proj_dir}docs/code/preprocessing/post_fmriprep_denoising.py ${subj}

echo 'Preparing for DCM '${subj}
mkdir -p ${pp_dir}${subj}/spm/scans/detrend_gsr_smooth6mm/
fslsplit ${proj_dir}data/derivatives/post-fmriprep-fix/${subj}/func/${subj}_task-rest_space-MNI152NLin2009cAsym_desc-detrend_gsr_smooth-6mm.nii.gz  ${pp_dir}${subj}/spm/scans/detrend_gsr_smooth6mm/${subj}_task-rest_space-MNI152NLin2009cAsym_desc-detrend_gsr_smooth-6mm
gzip -d ${pp_dir}${subj}/spm/scans/detrend_gsr_smooth6mm/*

echo 'Preparing '$subj' for SPM / seed-to-voxel analysis'
python ${proj_dir}docs/code/functional/seed_to_voxel_analysis.py --subj $subj --compute_seed_corr --unzip_corr_maps --merge_LR_hemis --n_jobs 1 --brain_smoothing_fwhm 8 --prep_fsl_randomise



